routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', 'HomePageController@index')->name('index');
Route::get('/profil', 'HomePageController@profile')->name('profile');
Route::get('/berita', 'HomePageController@berita')->name('berita');

Route::get('/berita/{id}', 'HomePageController@beritaDetail')->name('berita.detail');

Route::get('/galleries', 'HomePageController@galleries')->name('galleries');
Route::get('/archives', 'HomePageController@archives')->name('archives');
Route::get('/dosen', 'HomePageController@dosen')->name('dosen');
Route::get('/struktur-organisasi', 'HomePageController@StrukturOrganisasi')->name('struktur-organisasi');
Route::get('/kegiatan', 'HomePageController@kegiatan')->name('kegiatan');
Route::get('/alumni', 'HomePageController@alumni')->name('alumni');
Route::post('/alumni-landing', 'AlumniController@store')->name('landing.alumni.store');

Route::get('/logout', function () {
  Auth::logout();

  return redirect('/login');
})->name('logout');

Auth::routes();

Route::resource('alumni', 'AlumniController')->only('store');


Route::group(['middleware' => 'auth'], function () {
  Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomePageController@dashboard')->name('admin.dashboard');
    Route::get('password', 'ProfileController@password')->name('admin.get.password');
    Route::post('password', 'ProfileController@passwordPost')->name('admin.post.password');
    Route::get('profile', 'ProfileController@profile')->name('admin.get.profile');
    Route::post('profile', 'ProfileController@profilePost')->name('admin.post.profile');
    Route::resource('alumni', 'AlumniController')->except('store', 'show');
    Route::resource('user', 'UserController');
    Route::post('alumni/homepage/{id}', 'AlumniController@homepageManage')->name('alumni.homepage');
    Route::post('alumni/verif/{id}', 'AlumniController@verification')->name('alumni.verif');
    Route::get('alumni/print', 'AlumniController@print')->name('alumni.print');
    Route::resource('dosen', 'DosenController');
    Route::resource('struktur-organisasi', 'StrukturOrganisasiController')->except('create', 'show', 'edit');
    Route::resource('config', 'ConfigController')->only('index', 'update');
    Route::resource('welcome', 'SambutanController')->only('index', 'update');
    Route::resource('blog-categories', 'CategoryBlogController')->except('create', 'show', 'edit');
    Route::resource('gallery-categories', 'CategoryGalleryController')->except('create', 'show', 'edit');
    Route::resource('blog', 'BlogController');
    Route::post('blog/homepage/{id}', 'BlogController@homepageManage')->name('blog.homepage');
    Route::resource('gallery', 'GalleryController');
    Route::resource('kurikulum', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('kalender-akademik', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('jadwal-perkuliahan', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('berkas-kemahasiswaan', 'BerkasKemahasiswaanController')->except('create', 'show', 'edit');
    Route::resource('tahun-akademik', 'TahunAkademikController')->only('index', 'update');
  });
});

app/Models/Archives.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Archives extends Model
{
    protected $fillable = [
        'tahun',
        'file',
        'type',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public $timestamps = true;

    public function scopeFilter($query, $request)
    {
        $routeName = $request->route()->getName();
        if ($request->has('q')) {
            $query->where('tahun', 'like', '%' . $request->get('q') . '%');
        }

        switch ($routeName) {
            case 'kurikulum.index':
                $query->where('type', 'kurikulum');
                break;

            case 'jadwal-perkuliahan.index':
                $query->where('type', 'jadwal_perkuliahan');
                break;

            case 'kalender-akademik.index':
                $query->where('type', 'kalender_akademik');
                break;
            
            default:
                break;
        }

        return $query;
    }
}

app/Http/Controllers/ArchiveController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Models\Archives;
use Illuminate\Support\Str;

class ArchiveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $archives = Archives::Filter($request)->orderBy('tahun', 'DESC')->paginate(10);
        $routeName = $request->route()->getName();
        $module = explode('.', $routeName)[0];

        $view = [
            'datas'  => $archives
        ];

        switch ($module) {
            case 'jadwal-perkuliahan':
                $rturn = view('admin.archive.jadwal_perkuliahan.list')->with($view);
                break;
                
            case 'kalender-akademik':
                $rturn = view('admin.archive.kalender_akademik.list')->with($view);
            break;
            
            default:
                $rturn =  view('admin.archive.kurikulum.list')->with($view);
                break;
        }

        return $rturn;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $routeName = $request->route()->getName();
            $module = explode('.', $routeName)[0];

            switch ($module) {
                case 'jadwal-perkuliahan':
                    $type = 'jadwal_perkuliahan';
                    break;

                case 'kalender-akademik':
                    $type = 'kalender_akademik';
                    break;
                
                default:
                    $type = 'kurikulum';
                    break;
            }

            $file = $request->img;
            $slug = Str::slug($file->getClientOriginalName(), '_');
            $photo = time() . $slug . '.' . $file->getClientOriginalExtension();

            $this->SavePhotoNR($file, $photo, public_path('storage/' . $module . '/'));

            Archives::create([
                'tahun' => $request->tahun,
                'file' => $photo,
                'type' => $type
            ]);
    

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Menambahkan archive');
            $request->session()->flash('type', 'success');
    
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    private function SavePhotoNR($image, $photo, $path)
    {
        $file = $image;
        $file->move($path, $photo);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $routeName = $request->route()->getName();
            $module = explode('.', $routeName)[0];

            $archive = Archives::findOrFail($id);
            $archive->update([
                'tahun' => $request->tahun,
            ]);
    
            if (isset($request->img)) {
                if (!empty($archive->file)) {
                    \File::delete(public_path('storage/' . $module .  '/' . $archive->file));
                }
    
                $file = $request->img;
                $slug = Str::slug($file->getClientOriginalName(), '_');
                $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
                $archive->update(['file' => $photo]);
    
    
                $this->SavePhotoNR($file, $photo, public_path('storage/' . $module .'/'));
            }

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Mengubah Data Archive');
            $request->session()->flash('type', 'success');
    
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $routeName = $request->route()->getName();
            $module = explode('.', $routeName)[0];
            
            $archive = Archives::findOrFail($id);
            if (!empty($archive->file)) {
                \File::delete(public_path('storage/' . $module .  '/' . $archive->file));
            }
            
            $archive->delete();


            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data Archive');
            $request->session()->flash('type', 'success');
    
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }
}

resources/views/admin/archive/kurikulum/list.blade.php
@extends('admin.layouts.main')
 
@section('titlehome','Kurikulum')  

@section('content') 
    @include('admin.archive.kurikulum.templates.modal')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Kurikulum
            <small>List Kurikulum</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">List Kurikulum</li>
        </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            @if(Session::has('messages'))
              <div class="col-xs-12">
                <div class="alert alert-{{ Session::get('type') }} alert-relative alert-padding">
                  <button type="button" class="close" data-dismiss="alert"
                            aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <div>
                    {{ Session::get('messages') }}
                  </div>
                </div>
              </div>
            @endif
            <div class="row">
              <div class="col-md-12">
                <div class="card">
                  <div class="card-header">
                  <div class="d-flex">
                    @include('admin.components.search', ['placeholder' => 'Tahun'])
                    <div class="ml-auto">
                      <button type="button" class="btn btn-primary btn-add-modal-archive" data-url-add="{{ route('kurikulum.store') }}">Tambah Data</button>
                    </div>
                  </div>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered table-striped">
                        <thead class="thead-light">                  
                          <tr>
                            <th style="width: 10px">#</th>
                            <th>Tahun</th>
                            <th>File</th>
                            <th style="width: 40px">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($datas as $data)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $data->tahun }}</td>
                              <td><a href="{{ asset('storage/kurikulum/' . $data->file) }}" target="_blank"><button class="btn btn-info">Download</button></a></td>
                              <td class="d-flex">
                                <button type="button" 
                                        class="btn btn-success btn-edit-modal-archive mr-1" 
                                        data-tahun="{{ $data->tahun }}" 
                                        data-url-update="{{ route('kurikulum.update', $data->id) }}"
                                >Edit</button>
                                {{ Form::open(['route' => ['kurikulum.destroy', $data->id], 'onsubmit' => 'message(this, event)', 'data-message' => 'Ingin Menghapus Archive ini', 'method' => 'DELETE']) }}
                                    <button class="btn btn-danger">Hapus</button>
                                {{ Form::close() }}
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="card-footer d-flex justify-content-end">
                    {{ $datas->appends(request()->all())->links() }}
                  </div>
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')
  <script>
    $('.btn-add-modal-archive').click(function() {
      $('#modal-archive').modal('show');
      $('#modal-archive').find('#archive-form').attr('action', $(this).data('url-add'));
      $('#modal-archive').find('#tahun').val('');
      $('#modal-archive').find('.form-edit').hide();
      $('#modal-archive').find('.modal-title').html('Tambah Data Kurikulum');
      $( "input[name='_method']").attr('disabled', true);
    });

    $('.btn-edit-modal-archive').click(function() {
      $('#modal-archive').modal('show');
      $('#modal-archive').find('#archive-form').attr('action', $(this).data('url-update'));
      $('#modal-archive').find('#tahun').val($(this).data('tahun'));
      $('#modal-archive').find('.form-edit').show();
      $('#modal-archive').find('.modal-title').html('Edit Data Kurikulum');
      $( "input[name='_method']").attr('disabled', false);
    });
  </script>
@endsection