routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', 'HomePageController@index')->name('index');
Route::get('/profil', 'HomePageController@profile')->name('profile');
Route::get('/berita', 'HomePageController@berita')->name('berita');

Route::get('/berita/{id}', 'HomePageController@beritaDetail')->name('berita.detail');

Route::get('/galleries', 'HomePageController@galleries')->name('galleries');
Route::get('/archives', 'HomePageController@archives')->name('archives');
Route::get('/dosen', 'HomePageController@dosen')->name('dosen');
Route::get('/struktur-organisasi', 'HomePageController@StrukturOrganisasi')->name('struktur-organisasi');
Route::get('/kegiatan', 'HomePageController@kegiatan')->name('kegiatan');
Route::get('/alumni', 'HomePageController@alumni')->name('alumni');
Route::post('/alumni-landing', 'AlumniController@store')->name('landing.alumni.store');

Route::get('/logout', function () {
  Auth::logout();

  return redirect('/login');
})->name('logout');

Auth::routes();

Route::resource('alumni', 'AlumniController')->only('store');


Route::group(['middleware' => 'auth'], function () {
  Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomePageController@dashboard')->name('admin.dashboard');
    Route::get('password', 'ProfileController@password')->name('admin.get.password');
    Route::post('password', 'ProfileController@passwordPost')->name('admin.post.password');
    Route::get('profile', 'ProfileController@profile')->name('admin.get.profile');
    Route::post('profile', 'ProfileController@profilePost')->name('admin.post.profile');
    Route::resource('alumni', 'AlumniController')->except('store', 'show');
    Route::resource('user', 'UserController');
    Route::post('alumni/homepage/{id}', 'AlumniController@homepageManage')->name('alumni.homepage');
    Route::post('alumni/verif/{id}', 'AlumniController@verification')->name('alumni.verif');
    Route::get('alumni/print', 'AlumniController@print')->name('alumni.print');
    Route::resource('dosen', 'DosenController');
    Route::resource('struktur-organisasi', 'StrukturOrganisasiController')->except('create', 'show', 'edit');
    Route::resource('config', 'ConfigController')->only('index', 'update');
    Route::resource('welcome', 'SambutanController')->only('index', 'update');
    Route::resource('blog-categories', 'CategoryBlogController')->except('create', 'show', 'edit');
    Route::resource('gallery-categories', 'CategoryGalleryController')->except('create', 'show', 'edit');
    Route::resource('blog', 'BlogController');
    Route::post('blog/homepage/{id}', 'BlogController@homepageManage')->name('blog.homepage');
    Route::resource('gallery', 'GalleryController');
    Route::resource('kurikulum', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('kalender-akademik', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('jadwal-perkuliahan', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('berkas-kemahasiswaan', 'BerkasKemahasiswaanController')->except('create', 'show', 'edit');
    Route::resource('tahun-akademik', 'TahunAkademikController')->only('index', 'update');
  });
});

app/Models/Alumni.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Alumni extends Model
{
    protected $fillable = [
        'nama',
        'angkatan',
        'job_id',
        'telp',
        'quote',
        'verif',
        'homepage',
        'img',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'homepage' => 'boolean',
        'verif'    => 'boolean'
    ];

    public $timestamps = true;
    
    public function job()
    {
        return $this->belongsTo(PekerjaanAlumni::class, 'job_id');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('nama', 'like', '%' . $request->get('q') . '%')
                   ->orWhere('angkatan', 'like', '%' . $request->get('q') . '%')
                   ->orWhereHas('job', function($q) use($request) {
                        $q->where('name', 'like', '%' . $request->get('q') . '%');
                    })
                   ->orWhere('telp', 'like', '%' . $request->get('q') . '%');
        }

        if ($request->has('homepage')) {
            $query->where('homepage', $request->get('homepage'));
        }

        if ($request->has('verif')) {
            $query->where('verif', $request->get('verif'));
        }

        return $query;
    }
}

app/Http/Controllers/AlumniController.php
<?php

namespace App\Http\Controllers;

use DB;
use Excel;
use App\Models\Alumni;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Exports\AlumnisExport;
use App\Models\PekerjaanAlumni;

class AlumniController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $alumni = Alumni::filter($request)->with('job')->orderBy('nama', 'ASC')->paginate(10);
        $view = [
            'datas'  => $alumni
        ];

        return view('admin.alumni.list')->with($view);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jobs = PekerjaanAlumni::orderBy('id', 'ASC')->get();
        $views = [
            'jobs' => $jobs
        ];

        return view('admin.alumni.tambah')->with($views);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {

            $routeName = $request->route()->getName();
            $module = explode('.', $routeName)[0];
            
            $file = $request->img;
            $slug = Str::slug($file->getClientOriginalName(), '_');
            $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
            
            Alumni::create([
                'nama'              => $request->name,
                'angkatan'          => $request->tahun_angkatan,
                'job_id'            => $request->job_id,
                'telp'              => $request->no_telepon,
                'quote'             => $request->quote,
                'img'               => $photo
            ]);
            
            $this->SavePhotoNR($file, $photo, public_path('storage/alumnis/'));

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Menambahkan Data Alumni');
            $request->session()->flash('type', 'success');
            
            if ($module === 'alumni') {
                $redirect = redirect()->route('alumni.index');
            } else {
                $redirect = redirect()->route('index');
            }

            return $redirect;
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    private function SavePhotoNR($image, $photo, $path)
    {
        $file = $image;
        $file->move($path, $photo);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Alumni::findOrFail($id);
        $jobs = PekerjaanAlumni::orderBy('id', 'ASC')->get();

        $view = [
            'data'       => $data,
            'jobs'       => $jobs
        ];

        return view('admin.alumni.tambah')->with($view);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $alumni = Alumni::findOrFail($id);
            $alumni->update([
                'nama'              => $request->name,
                'angkatan'          => $request->tahun_angkatan,
                'job_id'            => $request->job_id,
                'telp'              => $request->no_telepon,
                'quote'             => $request->quote,
            ]);
    
            if (isset($request->img)) {
                if (!empty($alumni->img)) {
                    \File::delete(public_path('storage/alumnis/' . $alumni->img));
                }
    
                $file = $request->img;
                $slug = Str::slug($file->getClientOriginalName(), '_');
                $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
                $alumni->update(['img' => $photo]);
    
                $this->SavePhotoNR($file, $photo, public_path('storage/alumnis/'));
            }

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Mengubah Data Alumni');
            $request->session()->flash('type', 'success');
    
            return redirect()->route('alumni.index');
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $alumni = Alumni::findOrFail($id);
            if (!empty($alumni->img)) {
                \File::delete(public_path('storage/alumnis/' . $alumni->img));
            }
            
            $alumni->delete();

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data alumni');
            $request->session()->flash('type', 'success');
    
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    public function homepageManage (Request $request, $id) {
        DB::beginTransaction();
        try {
            $blog = Alumni::findOrFail($id);
            $blog->update([
                'homepage' => !$blog->homepage
            ]);

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Mengubah Status Alumni');
            $request->session()->flash('type', 'success');
    
            return redirect()->route('alumni.index');
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    public function verification (Request $request, $id) {
        DB::beginTransaction();
        try {
            $blog = Alumni::findOrFail($id);
            $blog->update([
                'verif' => true
            ]);

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Memverifikasi Alumni');
            $request->session()->flash('type', 'success');
    
            return redirect()->route('alumni.index');
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    public function print() {
        return Excel::download(new AlumnisExport, 'alumnis.xlsx');
    }
}

resources/views/admin/alumni/list.blade.php
@extends('admin.layouts.main')
 
@section('titlehome','Alumni')  

@section('content') 
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Alumni
            <small>List Alumni</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">List Alumni</li>
        </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            @if(Session::has('messages'))
              <div class="col-xs-12">
                <div class="alert alert-{{ Session::get('type') }} alert-relative alert-padding">
                  <button type="button" class="close" data-dismiss="alert"
                            aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <div>
                    {{ Session::get('messages') }}
                  </div>
                </div>
              </div>
            @endif
            <div class="row">
              <div class="col-md-12">
                <div class="card">
                  <div class="card-header">
                    <div class="d-flex">
                      @include('admin.components.search', ['placeholder' => 'Nama, Angkatan, Job, Telepon'])
                      <div class="pt-2">
                        <a href="{{ route('alumni.create') }}"><button type="button" class="btn btn-primary mr-1">Tambah Data</button></a>
                      </div>
                      <div class="pt-2">
                        <a href="{{ route('alumni.print') }}" title="print out" target="_blank"><button type="button" class="btn btn-success"><i class="fa fa-print"></i></button></a>
                      </div>
                    </div>
                    <div class="mt-2 mb-2">
                    @if(Request::has('verif') || Request::has('q') || Request::has('homepage'))
                        <a class="label label-info" href="{{ url('admin/alumni') }}">Semua</a>
                        <div class="clearfix"></div>
                        <br>
                    @endif
                    <a class="label label-primary" href="{{ url('admin/alumni?verif=1') }}">Terverifikasi</a>
                    <a class="label label-danger" href="{{ url('admin/alumni?verif=0') }}">Belum Diverifikasi</a>
                    <a class="label label-info" href="{{ url('admin/alumni?homepage=1') }}">Ditampilkan Dari Homepage</a>
                    <a class="label label-warning" href="{{ url('admin/alumni?homepage=0') }}">Disembunyikan Dari Homepage</a>
                  </div>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered table-striped">
                        <thead class="thead-light">                  
                          <tr>
                            <th style="width: 10px">#</th>
                            <th>Nama</th>
                            <th>Foto</th>
                            <th>Angkatan</th>
                            <th>Pekerjaan</th>
                            <th>No Telepon</th>
                            <th>verif</th>
                            <th>homepage</th>
                            <th style="width: 40px">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($datas as $data)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $data->nama }}</td>
                              <td>
                                <img src="{{ asset('storage/alumnis/' . $data->img) }}" class="img-thumbnail" style="height: 150px;width: 150px" alt="">
                              </td>
                              <td>{{ $data->angkatan }}</td>
                              <td>{{ $data->job->name }}</td>
                              <td>{{ $data->telp }}</td>
                              <th class="text-{{ $data->verif ? 'success' : 'danger' }}">{{ $data->verif ? 'Terverifikasi' : 'Belum Diverifikasi' }}</th>
                              <th>
                                {{ Form::open(['route' => ['alumni.homepage', $data->id], 'method' => 'POST']) }}
                                  <button class="btn btn-{{ $data->homepage ? 'success' : 'danger' }}" title="{{ $data->homepage ? 'Sembunyikan' : 'Tampilkan' }}">{{ $data->homepage ? 'Ditampilkan' : 'Disembunyikan' }}</button>
                                {{ Form::close() }}
                              </th>
                              <td class="d-flex">
                              <a href="{{ route('alumni.edit', $data->id ) }}"><button type="button" class="btn btn-success btn-edit-modal-blog mr-1">Edit</button></a>
                                {{ Form::open(['route' => ['alumni.destroy', $data->id], 'onsubmit' => 'message(this, event)', 'data-message' => 'Ingin Menghapus Data Alumni ini', 'method' => 'DELETE']) }}
                                  <button class="btn btn-danger mr-1">Hapus</button>
                                {{ Form::close() }}
                                @if(!$data->verif)
                                  {{ Form::open(['route' => ['alumni.verif', $data->id], 'onsubmit' => 'message(this, event)', 'data-message' => 'Ingin Memverifikasi Alumni ini', 'method' => 'POST']) }}
                                    <button class="btn btn-info" title="Verifikasi">Verifikasi</button>
                                  {{ Form::close() }}
                                @endif
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="card-footer d-flex justify-content-end">
                    {{ $datas->appends(request()->all())->links() }}
                  </div>
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/alumni/tambah.blade.php
@extends('admin.layouts.main')
 
@section('titlehome','Dashboard')  

@section('content') 
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            Alumni
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('alumni.index') }}"><i class="fa fa-newspaper-o"></i> Data Alumni</a></li>
            <li class="active">{{ isset($data) ? 'Edit' : 'Tambah' }} Data Alumni</li>
        </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          @if(Session::has('messages'))
            <div class="col-xs-12">
              <div class="alert alert-{{ Session::get('type') }} alert-relative alert-padding">
                <button type="button" class="close" data-dismiss="alert"
                          aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div>
                  {{ Session::get('messages') }}
                </div>
              </div>
            </div>
          @endif
          <div class="row">
            <div class="col-md-12">
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">{{ isset($data) ? 'Edit' : 'Tambah' }} Data Alumni</h3>
                </div>
                @if(isset($data))
                  {{ Form::open(['route' => ['alumni.update', $data->id], 'method' => 'PUT', 'files' => true]) }} 
                @else
                  {{ Form::open(['route' => ['alumni.store'], 'method' => 'POST', 'files' => true]) }} 
                @endif

                {{ Form::token() }}
                <div class="card-body">
                  <div class="form-group">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', isset($data) ? old('name', $data->nama) : old('name'), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Masukkan Nama', 'required' => true]) }}
                  </div>
                  <div class="form-group">
                    {{ Form::label('tahun_angkatan', 'Tahun Angkatan') }}
                    {{ Form::number('tahun_angkatan', isset($data) ? old('tahun_angkatan', $data->angkatan) : old('tahun_angkatan'), ['class' => 'form-control yearpickerLast', 'id' => 'tahun_angkatan', 'placeholder' => 'Masukkan Angkatan', 'required' => true]) }}
                  </div>
                  <div class="form-group">
                    {{ Form::label('job', 'Pekerjaan') }}
                    <select class="select_2 form-control" name="job_id" id="selected" required>
                      <option value=""></option>
                      @foreach($jobs as $job)
                        <option value="{{ $job->id }}">{{ $job->name }}</option>
                      @endforeach
                    </select>
                  </div>
                  <div class="form-group">
                    {{ Form::label('no_telepon', 'Nomor Telepon') }}
                    {{ Form::number('no_telepon', isset($data) ? old('no_telepon', $data->telp) : old('no_telepon'), ['class' => 'form-control', 'id' => 'no_telepon', 'placeholder' => 'Masukkan Nomor Telepon', 'required' => true]) }}
                  </div>
                  <div class="form-group">
                    {{ Form::label('quote', 'Quote') }}
                    <textarea class="form-control" id="quote" name="quote" placeholder="Desription" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ isset($data) ? old('quote', $data->quote) : old('quote') }}</textarea>
                  </div>
                  <label for="">Gambar</label>
                  @if(isset($data))
                    <div class="form-group">
                      <img src="{{ asset('storage/alumnis/' . $data->img) }}" class="img-thumbnail" style="height: 300px;" alt="">
                    </div>
                  @endif

                  <label for="">Upload gambar Baru</label>
                  <div class="form-group">
                    {{ Form::file('img', ['class' => 'form-control pb-2', 'accept' => 'image/*', isset($data) ?? 'required' => true]) }}
                    <div class="border">
                      <ul class="pt-2">
                      @if(isset($data))
                        <li>Pilih gambar untuk mengubah gambar</li>
                        <li>Tidak perlu pilih gambar jika tidak ingin mengubah gambar</li>
                      @endif
                      <li>File harus gambar</li>
                    </ul>
                    </div>
                  </div>
                </div>
                <div class="card-footer clearfix">
                  <div class="col-12">
                    {{ Form::submit('Save changes', ['class' => 'btn btn-success float-right']) }}
                  </div>
                </div>
                {{ Form::close() }}
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
          </div>
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')
  <script>
    @if(isset($data))
      $("#selected").val({{  $data->job_id }}).trigger('change');
    @endif
  </script>

@endsection