routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', 'HomePageController@index')->name('index');
Route::get('/profil', 'HomePageController@profile')->name('profile');
Route::get('/berita', 'HomePageController@berita')->name('berita');

Route::get('/berita/{id}', 'HomePageController@beritaDetail')->name('berita.detail');

Route::get('/galleries', 'HomePageController@galleries')->name('galleries');
Route::get('/archives', 'HomePageController@archives')->name('archives');
Route::get('/dosen', 'HomePageController@dosen')->name('dosen');
Route::get('/struktur-organisasi', 'HomePageController@StrukturOrganisasi')->name('struktur-organisasi');
Route::get('/kegiatan', 'HomePageController@kegiatan')->name('kegiatan');
Route::get('/alumni', 'HomePageController@alumni')->name('alumni');
Route::post('/alumni-landing', 'AlumniController@store')->name('landing.alumni.store');

Route::get('/logout', function () {
  Auth::logout();

  return redirect('/login');
})->name('logout');

Auth::routes();

Route::resource('alumni', 'AlumniController')->only('store');


Route::group(['middleware' => 'auth'], function () {
  Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomePageController@dashboard')->name('admin.dashboard');
    Route::get('password', 'ProfileController@password')->name('admin.get.password');
    Route::post('password', 'ProfileController@passwordPost')->name('admin.post.password');
    Route::get('profile', 'ProfileController@profile')->name('admin.get.profile');
    Route::post('profile', 'ProfileController@profilePost')->name('admin.post.profile');
    Route::resource('alumni', 'AlumniController')->except('store', 'show');
    Route::resource('user', 'UserController');
    Route::post('alumni/homepage/{id}', 'AlumniController@homepageManage')->name('alumni.homepage');
    Route::post('alumni/verif/{id}', 'AlumniController@verification')->name('alumni.verif');
    Route::get('alumni/print', 'AlumniController@print')->name('alumni.print');
    Route::resource('dosen', 'DosenController');
    Route::resource('struktur-organisasi', 'StrukturOrganisasiController')->except('create', 'show', 'edit');
    Route::resource('config', 'ConfigController')->only('index', 'update');
    Route::resource('welcome', 'SambutanController')->only('index', 'update');
    Route::resource('blog-categories', 'CategoryBlogController')->except('create', 'show', 'edit');
    Route::resource('gallery-categories', 'CategoryGalleryController')->except('create', 'show', 'edit');
    Route::resource('blog', 'BlogController');
    Route::post('blog/homepage/{id}', 'BlogController@homepageManage')->name('blog.homepage');
    Route::resource('gallery', 'GalleryController');
    Route::resource('kurikulum', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('kalender-akademik', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('jadwal-perkuliahan', 'ArchiveController')->except('create', 'show', 'edit');
    Route::resource('berkas-kemahasiswaan', 'BerkasKemahasiswaanController')->except('create', 'show', 'edit');
    Route::resource('tahun-akademik', 'TahunAkademikController')->only('index', 'update');
  });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Models\Blog;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'img'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('name', 'like', '%' . $request->get('q') . '%')
                  ->orWhere('email', 'like', '%' . $request->get('q') . '%');
        }

        return $query;
    }

    public function blogs() {
        return $this->hasMany(Blog::class, 'user_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = User::filter($request)->with('blogs')->whereNotIn('id', [1])->orderBy('name', 'ASC')->paginate(10);
        $view = [
            'datas'  => $user
        ];

        return view('admin.user.list')->with($view);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        DB::beginTransaction();
        try {
            
            $file = $request->img;
            $slug = Str::slug($file->getClientOriginalName(), '_');
            $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
            
            User::create([
                'name'              => $request->name,
                'email'             => $request->email,
                'password'          => bcrypt($request->password),
                'img'               => $photo
            ]);
            
            $this->SavePhotoNR($file, $photo, public_path('storage/users/'));

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Menambahkan Data User');
            $request->session()->flash('type', 'success');
    
            return redirect()->route('user.index');
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    private function SavePhotoNR($image, $photo, $path)
    {
        $file = $image;
        $file->move($path, $photo);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::findOrFail($id);
        $view = [
            'data'       => $data,
        ];

        return view('admin.user.tambah')->with($view);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $user = User::findOrFail($id);
            $user->update([
                'name'        => $request->name,
            ]);
    
            if (isset($request->img)) {
                if (!empty($user->img)) {
                    \File::delete(public_path('storage/users/' . $user->img));
                }
    
                $file = $request->img;
                $slug = Str::slug($file->getClientOriginalName(), '_');
                $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
                $user->update(['img' => $photo]);
    
                $this->SavePhotoNR($file, $photo, public_path('storage/users/'));
            }

            DB::commit();
            
            $request->session()->flash('messages', 'Berhasil Mengubah Data user');
            $request->session()->flash('type', 'success');
    
            return redirect()->route('user.index');
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        DB::beginTransaction();
        try {
            $user = User::findOrFail($id);
            if (!empty($user->img)) {
                \File::delete(public_path('storage/users/' . $user->img));
            }
            
            $user->delete();

            DB::commit();

            $request->session()->flash('messages', 'Berhasil Menghapus Data User');
            $request->session()->flash('type', 'success');
    
            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
        
            return $e->getMessage();
        }
    }
}

resources/views/admin/user/list.blade.php
@extends('admin.layouts.main')
 
@section('titlehome','User')  

@section('content') 
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            User
            <small>List User</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">List User</li>
        </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
          @if(Session::has('messages'))
            <div class="col-xs-12">
              <div class="alert alert-{{ Session::get('type') }} alert-relative alert-padding">
                <button type="button" class="close" data-dismiss="alert"
                          aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div>
                  {{ Session::get('messages') }}
                </div>
              </div>
            </div>
          @endif
            <div class="row">
              <div class="col-md-12">
                <div class="card">
                  <div class="card-header">
                  <div class="d-flex">
                    @include('admin.components.search', ['placeholder' => 'Nama, Email'])
                    <div class="ml-auto">
                       <a href="{{ route('user.create') }}"><button type="button" class="btn btn-primary">Tambah Data</button></a>
                    </div>
                  </div>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered table-striped">
                        <thead class="thead-light">                  
                          <tr>
                            <th style="width: 10px">#</th>
                            <th>Nama</th>
                            <th>Foto</th>
                            <th>Email</th>
                            <th style="width: 40px">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($datas as $data)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $data->name }}</td>
                              <td>
                                <img src="{{ asset('storage/users/' . $data->img) }}" class="img-thumbnail" style="height: 150px;width: 150px" alt="">
                              </td>
                              <td>{{ $data->email }}</td>
                              <td class="d-flex">
                              @if(auth()->user()->id === 1)
                                <a href="{{ route('user.edit', $data->id ) }}"><button type="button" class="btn btn-success btn-edit-modal-blog mr-1">Edit</button></a>
                                @if($data->blogs->count() === 0) 
                                  {{ Form::open(['route' => ['user.destroy', $data->id], 'onsubmit' => 'message(this, event)', 'data-message' => 'Ingin Menghapus Data user ini', 'method' => 'DELETE']) }}
                                    <button class="btn btn-danger mr-1">Hapus</button>
                                  {{ Form::close() }}
                                @else
                                  <button type="button" class="btn btn-default" onclick="messageDefault('Gagal menghapus', 'Tidak Bisa menghapus karena sudah membuat blog', 'error')" style="cursor:not-allowed">Hapus</button>
                                @endif
                              @else
                              -
                              @endif
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="card-footer d-flex justify-content-end">
                    {{ $datas->appends(request()->all())->links() }}
                  </div>
                </div>
                <!-- /.card -->
              </div>
              <!-- /.col -->
            </div>
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/user/tambah.blade.php
@extends('admin.layouts.main')
 
@section('titlehome','Dashboard')  

@section('content') 
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
        <h1>
            User
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{ route('user.index') }}"><i class="fa fa-newspaper-o"></i> Data User</a></li>
            <li class="active">{{ isset($data) ? 'Edit' : 'Tambah' }} Data User</li>
        </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          @if(Session::has('messages'))
            <div class="col-xs-12">
              <div class="alert alert-{{ Session::get('type') }} alert-relative alert-padding">
                <button type="button" class="close" data-dismiss="alert"
                          aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <div>
                  {{ Session::get('messages') }}
                </div>
              </div>
            </div>
          @endif
          <div class="row">
            <div class="col-md-12">
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">{{ isset($data) ? 'Edit' : 'Tambah' }} Data User</h3>
                </div>
                @if(isset($data))
                  {{ Form::open(['route' => ['user.update', $data->id], 'method' => 'PUT', 'files' => true]) }} 
                @else
                {{ Form::open(['route' => ['user.store'], 'method' => 'POST', 'files' => true]) }} 
                @endif

                {{ Form::token() }}
                <div class="card-body">
                  <div class="form-group">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', isset($data) ? old('name', $data->name) : old('name'), ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Masukkan Nama', 'required' => true]) }}
                    @error('name')
                      <div class="error text-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  @if(!isset($data))
                    <div class="form-group">
                      {{ Form::label('email', 'Email') }}
                      {{ Form::email('email', isset($data) ? old('email', $data->email) : old('email'), ['class' => 'form-control', 'id' => 'email', 'placeholder' => 'Masukkan Email', 'required' => true]) }}
                      @error('email')
                        <div class="error text-danger">{{ $message }}</div>
                      @enderror
                    </div>
                  @endif
                  @if(!isset($data))
                    <div class="form-group">
                      {{ Form::label('password', 'Password') }}
                      {{ Form::password('password', ['class' => 'form-control', 'id' => 'password', 'placeholder' => 'Masukkan Password', 'required' => true, 'min' => 6, 'max' => '20']) }}
                      @error('password')
                        <div class="error text-danger">{{ $message }}</div>
                      @enderror
                    </div>
                  @endif
                  <label for="">Gambar</label>
                  @if(isset($data))
                    <div class="form-group">
                      <img src="{{ asset('storage/users/' . $data->img) }}" class="img-thumbnail" style="height: 300px;" alt="">
                    </div>
                  @endif

                  <label for="">Upload gambar Baru</label>
                  <div class="form-group">
                    {{ Form::file('img', ['class' => 'form-control pb-2', 'accept' => 'image/*', isset($data) ?? 'required' => true]) }}
                    <div class="border">
                      <ul class="pt-2">
                      @if(isset($data))
                        <li>Pilih gambar untuk mengubah gambar</li>
                        <li>Tidak perlu pilih gambar jika tidak ingin mengubah gambar</li>
                      @endif
                      <li>File harus gambar</li>
                    </ul>
                    </div>
                  </div>
                </div>
                <div class="card-footer clearfix">
                  <div class="col-12">
                    {{ Form::submit('Save changes', ['class' => 'btn btn-success float-right']) }}
                  </div>
                </div>
                {{ Form::close() }}
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
          </div>
        </section>
        <!-- /.content -->
    </div>
@endsection